#!/bin/zsh

## bash keep complaining about null bytes almost everywhere, used zsh

_saved=`xclip -o -se c`
xclip -se c </dev/null

while read file
do
	[[ ! $file = /* ]] && file=`pwd`/`sed 's@^\\./@@;s/\n$//' <<< $file`
	case $1 in
		y)
			echo -ne "`xclip -o -se c`$Z$file" | xclip -se c
			Z=$'\0' # to not append a NUL to a single file
			;;
		w) xwallpaper --zoom "$file";rm -f .config/bg; ln -s "$file" .config/bg;;
#		C-w) set-theme "$file" ;;
	esac
done

[ -z "`xclip -o -se c`" ] && echo -n $_saved | xclip -se c \
	|| xclip -o -se c | xclip -se c
