#!/bin/bash

source ~/.config/lf/icons.sh

set -e

if [ -n "$DISPLAY" ]; then
  export FIFO_UEBERZUG="/tmp/lf-ueberzug-$$"

  cleanup() {
    exec 3>&-
    rm "$FIFO_UEBERZUG" -f
  }

  mkfifo "$FIFO_UEBERZUG"
  ueberzug layer -s <"$FIFO_UEBERZUG" &
  exec 3>"$FIFO_UEBERZUG"
  trap cleanup EXIT

  mkdir -p "$HOME/.cache/lf"

  exec /bin/lf $@ 3>&-
else
  exec /bin/lf $@
fi
