#!/bin/bash

while true; do

    echo -ne "\e[5 q" # keep beam cursor

    selected=$(find * desk/* -maxdepth 0 -type d ! -name .\* | fzf --layout=reverse)

    if [[ -z "$selected" ]]; then
        break
    fi

    if [[ ! -d "$selected" ]]; then
        mkdir -p "$selected"
        if [[ $? != 0 ]]; then
            echo "Can't create the directory"
            exit 1
        fi
    fi

    selected_name=$(basename "$selected" | tr . _ | tr '-' _)

    tmux new-session -As $selected_name -c $selected -e fish_history=$selected_name
done
